### ISSUE TITLE
How do use this package in Python?

### ISSUE THREAD

**Issue by fmenegui** [KitwareMedical/ITKStrain#44]
Hello,

I am trying to use functions from the ITKStrain package in Python. I have only seen examples in C++. Are there any available resources in Python, i.e., code examples?

Thank you.

**Comment by tbirdso** [comment]
Per discussion on the [ITK Discourse forums](https://discourse.itk.org/t/vector-image-to-image-of-vectors/4385/5), the most elegant solution here is to use `itk.cast_image_filter` to convert from `VectorImage` to an `Image` of vectors (thanks @dzenanz !). The process for getting strain from a numpy array is then:

1. Convert to ITK VectorImage: `vector_image = itk.image_from_array(displacements_array.astype(np.float32, is_vector=True)`
2. Convert to ITK Image: `image = itk.cast_image_filter(vector_image, ttype=[type(vector_image), itk.Image[itk.Vector[itk.F,2],2]])`
3. Use `itkStrainImageFilter` to compute strain as described in the comments above.

**Comment by tbirdso** [comment]
Hi @fmenegui, please see the newly added example [notebook](https://github.com/KitwareMedical/ITKStrain/blob/master/examples/StrainFromNumpy.ipynb) or [script](https://github.com/KitwareMedical/ITKStrain/blob/master/examples/numpy_to_strain.py) for a demonstration of using the `itk-strain` Python package with `numpy` arrays.

I'm closing this issue but feel free to reopen if you have additional questions.
