### ISSUE TITLE
Publish to PyPi Failed

### ISSUE THREAD

**Issue by tbirdso** [KitwareMedical/ITKStrain#49]
Tagged version v0.3.5 otherwise passes CI but failed to upload to PyPi.

@thewtex @dzenanz Have you seen this issue before or can we manually upload the updated package to PyPi?

Full log: [https://github.com/KitwareMedical/ITKStrain/runs/3548041719?check_suite_focus=true](https://github.com/KitwareMedical/ITKStrain/runs/3548041719?check_suite_focus=true)

Error message:
> Run actions/download-artifact@v2
No artifact name specified, downloading all artifacts
Creating an extra directory for each artifact that is being downloaded
Total number of files that will be downloaded: 1
Total number of files that will be downloaded: 1
Total number of files that will be downloaded: 1
Get Container Items - Error is not retryable
##### Begin Diagnostic HTTP information #####
Status Code: 404
Status Message: Not Found
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "content-length": "311",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "58b9b9a1-9e35-41d6-a4b8-328098d3f4ca",
  "activityid": "79872053-713c-4754-bb74-3abf797e3e87",
  "x-tfs-session": "79872053-713c-4754-bb74-3abf797e3e87",
  "x-vss-e2eid": "79872053-713c-4754-bb74-3abf797e3e87",
  "x-vss-senderdeploymentid": "a07ab14e-025a-39c3-8d53-788cd7ce207f",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: BDF7C7E4BE2044008522F08F992DD373 Ref B: STBEDGE0208 Ref C: 2021-09-08T18:12:47Z",
  "date": "Wed, 08 Sep 2021 18:12:46 GMT",
  "connection": "close"
}
##### Begin Diagnostic HTTP information #####
Status Code: 404
Status Message: Not Found
Header Information: {
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "content-length": "311",
  "content-type": "application/json; charset=utf-8",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "58b9b9a1-9e35-41d6-a4b8-328098d3f4ca",
  "activityid": "79872053-713c-4754-bb74-3abf797e3e87",
  "x-tfs-session": "79872053-713c-4754-bb74-3abf797e3e87",
  "x-vss-e2eid": "79872053-713c-4754-bb74-3abf797e3e87",
  "x-vss-senderdeploymentid": "a07ab14e-025a-39c3-8d53-788cd7ce207f",
  "x-frame-options": "SAMEORIGIN",
  "x-cache": "CONFIG_NOCACHE",
  "x-msedge-ref": "Ref A: BDF7C7E4BE2044008522F08F992DD373 Ref B: STBEDGE0208 Ref C: 2021-09-08T18:12:47Z",
  "date": "Wed, 08 Sep 2021 18:12:46 GMT",
  "connection": "close"
}
###### End Diagnostic HTTP information ######
Error: Get Container Items failed: Artifact service responded with 404

**Comment by dzenanz** [comment]
Seems like a problem in GitHub.

**Comment by thewtex** [comment]
Yes, possibly a temporary issue with GitHub.

I hit the *Re-run jobs* button, and the build completed 🤷‍♂️
